### ISSUE TITLE
Feature Request Heizkreis 3

### ISSUE THREAD

**Issue by onesystemtechnik** [challo2018/LoxBerry-Plugin-Vitoconnect#10]
Hi, ich benötige die Möglichkeit an einem dritten Heizkreis diese Variablen zu beschreiben. 

Weiterhin wäre es Cool wenn man von einer Wärmepumpe den Stromverbrauch ins MQTT geschrieben bekommt. 

Bin gerne bereit zu unterstützen.

Gruß Oli

/admin/plugins/Vitoconnect/vitoconnect.php?action=setvalue&option=heating.circuits.2.operating.programs.normal&value=<v>

/admin/plugins/Vitoconnect/vitoconnect.php?action=setvalue&option=heating.circuits.2.operating.modes.active&commands&setMode&value=<v>

**Comment by challo2018** [comment]
Hi, das Thema Heizkreis ist kein Problem, kann ich einfügen. Ansonsten wird alles was die API zur Verfügung stellt auf mqtt übertragen. Schau Mal auf der Seite des Viessmann Developer Portal. Da gibt's eine Übersicht über die verschiedenen Pläne, eventuell ist das was dir fehlt kostenpflichtig.

**Comment by onesystemtechnik** [comment]
ok, merci. Bin neu hier auf GitHub, wie bekomme ich deine Änderungen bezüglich des Heizkreis 3?

Die Sollten kostenlos sein, sehe die Werte auch in der App. 

![Screenshot 2024-01-03 191059](https://github.com/challo2018/LoxBerry-Plugin-Vitoconnect/assets/155568044/78bc8d14-6dc0-414f-9fb6-ee32aa38185c)

**Comment by challo2018** [comment]
Ich sehe die Werte auch in der App aber über die API bekomme ich nichts. Weiß leider nicht an was es liegt. 
Installier mal PreRelease Version 0.2.2 und schau dann mal ins Log-File. Dort müsstest du die Rohdaten sehen die von der API kommen. Da kannst du nach heating.power suchen. 

Eine neue Version des Plugins bekommst du automatich auf dein loxberry wenn du Autoupdate und prerelease bei dem Plugin aktivierst.

**Comment by onesystemtechnik** [comment]
![Screenshot 2024-01-04 131857](https://github.com/challo2018/LoxBerry-Plugin-Vitoconnect/assets/155568044/08a0cc57-0c98-42a3-bd23-6328be0340c6)

Hi, ich hab die 0.2.2 installiert, bekomme die Logs auch aufgelistet aber nicht geöffnet...

**Comment by challo2018** [comment]
@onesystemtechnik : Sorry mach bitte nochmal ein Update auf die 0.2.3. Hier funktioniert das Logging richtig. 
Die SET Values integriere ich heute abend.

**Comment by onesystemtechnik** [comment]
Hi, logging hat geklappt. Merci

Konntest du schon die Heizkreise integrieren?

Danke!

**Comment by challo2018** [comment]
> Hi, logging hat geklappt. Merci
> 
> Konntest du schon die Heizkreise integrieren?
> 
> Danke!

Hab gerade Version 0.2.4 erstellt. Damit sollte das setzen funktionieren.

**Comment by challo2018** [comment]
@onesystemtechnik : Meld dich wenn es noch ein Thema gibt. Ansonsten erstelle ich ein Release und schließe das Thema hier

**Comment by onesystemtechnik** [comment]
Hi, funktioniert alles! Vielen Dank.

Weißt du ob es eine Smart grid Funktion gibt?

Der Verdichter geht ja trotz Erhöhung der Sollwerte gelegentlich in den standby...

Ansonsten gerne das Release erstellen :-)

**Comment by challo2018** [comment]
Sehr gut, ich erstelle ein neues Release.
SmartGrid funktioniert soweit ich weiß nur über Hardwarekontakte oder Modbus, nicht über die API...
Bin da leider mit der teuren Viessmann Wärmepumpe im Bezug auf smartHome Funktionen nicht sehr zufrieden.
